using BluePrintHr.Api.Models;

namespace BluePrintHr.Api.Contracts;

public record LoginRequest(string Email, string Password);
public record UserDto(int Id, string Name, string Email, string Role, int TenantId, int? EmployeeId);
public record TenantDto(int Id, string CompanyName, string? KraPin, string? Email, string? Phone, string? Address, string Status);
public record DashboardDto(int TotalEmployees, decimal MonthlyGross, int Branches, int Departments, string PayrollStatus, TenantDto Tenant, UserDto User);
public record EmployeeDto(int Id, string EmployeeNo, string? PayrollNo, string FullName, string FirstName, string? MiddleName, string LastName, string? Email, string? Phone, string KraPin, string? NssfNo, string? ShifNo, string EmploymentStatus, decimal BasicSalary, string? BankName, string? BankBranch, string? AccountNumber, int? DepartmentId, int? BranchId, int? DesignationId, int? GradeId, int? EmploymentTypeId, DateTime? EmploymentDate, DateTime? TerminationDate);
public record CreateEmployeeRequest(string EmployeeNo, string FirstName, string LastName, string KraPin, decimal BasicSalary, string? MiddleName, string? PayrollNo, string? Email, string? Phone, string? NssfNo, string? ShifNo, int? BranchId, int? DepartmentId, string? BankName, string? BankBranch, string? AccountNumber);
public record UpdateEmployeeRequest(string EmployeeNo, string FirstName, string LastName, string KraPin, decimal BasicSalary, string? MiddleName, string? PayrollNo, string? Email, string? Phone, string? NssfNo, string? ShifNo, int? BranchId, int? DepartmentId, int? DesignationId, int? GradeId, int? EmploymentTypeId, DateTime? EmploymentDate, DateTime? TerminationDate, string EmploymentStatus, string? BankName, string? BankBranch, string? AccountNumber);
public record CreateBranchRequest(string Name, string? Code, string? Location);
public record CreateDepartmentRequest(string Name, string? Code, int? BranchId);
public record UpdateBranchRequest(string Name, string? Code, string? Location);
public record UpdateDepartmentRequest(string Name, string? Code, int? BranchId);
public record CreateDesignationRequest(string Name);
public record UpdateDesignationRequest(string Name);
public record CreateGradeRequest(string Name, string? Level, decimal MinSalary, decimal MaxSalary);
public record UpdateGradeRequest(string Name, string? Level, decimal MinSalary, decimal MaxSalary);
public record CreateEmploymentTypeRequest(string Name, string? Description);
public record UpdateEmploymentTypeRequest(string Name, string? Description);
public record CreateLeaveTypeRequest(string Name, int DefaultDays, bool Paid, string? Description);
public record UpdateLeaveTypeRequest(string Name, int DefaultDays, bool Paid, string? Description);
public record OrganizationDto(IReadOnlyList<Branch> Branches, IReadOnlyList<Department> Departments, IReadOnlyList<Designation> Designations, IReadOnlyList<Grade> Grades, IReadOnlyList<EmploymentType> EmploymentTypes);
public record PayrollPeriodDto(int Id, string Name, int Month, int Year, string Status, DateTime? ProcessedAt);
public record CreatePayrollPeriodRequest(int Month, int Year);
public record PayrollTransactionDto(int Id, int EmployeeId, string EmployeeName, decimal GrossPay, decimal Paye, decimal Nssf, decimal Shif, decimal HousingLevy, decimal TotalDeductions, decimal NetPay, string Status);
public record PayrollProcessRequest(int PayrollPeriodId, decimal Allowances = 0, decimal OtherDeductions = 0);
public record PayrollComponentDto(int Id, int EmployeeId, string Name, string ComponentType, decimal Amount, bool Taxable, bool Recurring, bool Active);
public record CreatePayrollComponentRequest(int EmployeeId, string Name, string ComponentType, decimal Amount, bool Taxable = true, bool Recurring = true);
public record UpdatePayrollComponentRequest(string Name, string ComponentType, decimal Amount, bool Taxable, bool Recurring, bool Active);
public record NotificationDto(int Id, string Type, string Title, string Message, string? EntityType, int? EntityId, bool IsRead, DateTime CreatedAt);
public record LeaveTypeDto(int Id, string Name, int DefaultDays, bool Paid, string? Description);
public record LeaveBalanceDto(int Id, int EmployeeId, int LeaveTypeId, string LeaveType, int Year, decimal AllocatedDays, decimal UsedDays, decimal AvailableDays);
public record LeaveRequestDto(int Id, int EmployeeId, string EmployeeName, int LeaveTypeId, string LeaveType, DateTime StartDate, DateTime EndDate, decimal DaysRequested, string? Reason, string Status, DateTime CreatedAt);
public record CreateLeaveRequest(int EmployeeId, int LeaveTypeId, DateTime StartDate, DateTime EndDate, decimal DaysRequested, string? Reason);
public record UpdateLeaveStatusRequest(LeaveRequestStatus Status);
public record AuditLogDto(int Id, string Action, string EntityType, int? EntityId, string? UserName, string? Details, DateTime CreatedAt);
public record ReportDefinitionDto(int Id, string Name, string Description, string ReportPath, string? LaunchUrl);
public record ReportDataDto(string Name, string Description, IReadOnlyList<string> Columns, IReadOnlyList<IReadOnlyList<string>> Rows, DateTime GeneratedAt);

public record AttendanceDto(int Id, int EmployeeId, string EmployeeName, string EmployeeNo, DateTime AttendanceDate, DateTime? CheckIn, DateTime? CheckOut, string Status, decimal HoursWorked, string? Notes);
public record AttendanceSummaryDto(DateTime From, DateTime To, int Present, int Late, int Absent, int Leave, int HalfDay, decimal HoursWorked);
public record CreateAttendanceRequest(int EmployeeId, DateTime AttendanceDate, DateTime? CheckIn, DateTime? CheckOut, AttendanceStatus Status, decimal? HoursWorked, string? Notes);
