-- Effective-dated Kenya payroll tax tables.
-- PAYE rates sourced from KRA's published individual income tax bands.
-- NSSF 2026 Year 4, SHIF and Housing Levy are represented as configurable statutory tables.

create table if not exists public.payroll_tax_tables (
  id integer generated by default as identity primary key,
  tenant_id integer references public.tenants(id) on delete cascade,
  tax_type text not null,
  name text not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  rate numeric(9,6),
  employer_rate numeric(9,6),
  personal_relief numeric(18,2),
  minimum_amount numeric(18,2),
  maximum_amount numeric(18,2),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists ix_payroll_tax_tables_lookup
  on public.payroll_tax_tables(tenant_id,tax_type,effective_from);

create table if not exists public.payroll_tax_bands (
  id integer generated by default as identity primary key,
  payroll_tax_table_id integer not null references public.payroll_tax_tables(id) on delete cascade,
  lower_bound numeric(18,2) not null,
  upper_bound numeric(18,2),
  rate numeric(9,6) not null,
  sort_order integer not null,
  unique(payroll_tax_table_id,sort_order)
);

insert into public.payroll_tax_tables
(tax_type,name,effective_from,effective_to,personal_relief,active)
select 'PAYE','Kenya PAYE 2023+','2023-07-01',null,2400,true
where not exists (select 1 from public.payroll_tax_tables where tenant_id is null and tax_type='PAYE' and effective_from='2023-07-01');

insert into public.payroll_tax_bands(payroll_tax_table_id,lower_bound,upper_bound,rate,sort_order)
select t.id, v.lower_bound, v.upper_bound, v.rate, v.sort_order
from public.payroll_tax_tables t
cross join (values
 (0::numeric,24000::numeric,0.10::numeric,1),
 (24000::numeric,32333::numeric,0.25::numeric,2),
 (32333::numeric,500000::numeric,0.30::numeric,3),
 (500000::numeric,800000::numeric,0.325::numeric,4),
 (800000::numeric,null,0.35::numeric,5)
) v(lower_bound,upper_bound,rate,sort_order)
where t.tenant_id is null and t.tax_type='PAYE' and t.effective_from='2023-07-01'
and not exists (select 1 from public.payroll_tax_bands b where b.payroll_tax_table_id=t.id);

insert into public.payroll_tax_tables
(tax_type,name,effective_from,rate,maximum_amount,active)
select 'NSSF','NSSF Year 4 2026','2026-02-01',0.06,108000,true
where not exists (select 1 from public.payroll_tax_tables where tenant_id is null and tax_type='NSSF' and effective_from='2026-02-01');

insert into public.payroll_tax_tables
(tax_type,name,effective_from,rate,active)
select 'SHIF','SHIF statutory contribution','2024-10-01',0.0275,true
where not exists (select 1 from public.payroll_tax_tables where tenant_id is null and tax_type='SHIF' and effective_from='2024-10-01');

insert into public.payroll_tax_tables
(tax_type,name,effective_from,rate,employer_rate,active)
select 'HousingLevy','Affordable Housing Levy','2024-03-19',0.015,0.015,true
where not exists (select 1 from public.payroll_tax_tables where tenant_id is null and tax_type='HousingLevy' and effective_from='2024-03-19');

alter table public.payroll_tax_tables enable row level security;
alter table public.payroll_tax_bands enable row level security;
