-- Authentication/account hardening: activation, session invalidation and password reset tokens.
alter table public.users add column if not exists active boolean not null default true;
alter table public.users add column if not exists security_stamp text not null default gen_random_uuid()::text;

create table if not exists public.password_reset_tokens (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  token_hash text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now(),
  requested_ip text
);
create unique index if not exists ix_password_reset_tokens_hash on public.password_reset_tokens(token_hash);
create index if not exists ix_password_reset_tokens_user on public.password_reset_tokens(user_id,expires_at);
alter table public.password_reset_tokens enable row level security;
