create table if not exists public.attendance_records (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  employee_id integer not null references public.employees(id) on delete restrict,
  attendance_date date not null,
  check_in timestamptz,
  check_out timestamptz,
  status text not null default 'Present',
  hours_worked numeric(5,2) not null default 0,
  notes text,
  created_at timestamptz not null default now()
);
create unique index if not exists ix_attendance_records_tenant_employee_date on public.attendance_records(tenant_id, employee_id, attendance_date);
create index if not exists ix_attendance_records_tenant_date on public.attendance_records(tenant_id, attendance_date);
alter table public.attendance_records enable row level security;