create table if not exists public.employee_payroll_components (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  employee_id integer not null references public.employees(id) on delete cascade,
  name text not null,
  component_type text not null default 'Allowance',
  amount numeric(18,2) not null,
  taxable boolean not null default true,
  recurring boolean not null default true,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists ix_employee_payroll_components_tenant_employee_active
on public.employee_payroll_components(tenant_id, employee_id, active);

create table if not exists public.notifications (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  user_id integer not null references public.users(id) on delete cascade,
  type text not null default 'Info',
  title text not null,
  message text not null,
  entity_type text,
  entity_id integer,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists ix_notifications_tenant_user_read_created
on public.notifications(tenant_id, user_id, is_read, created_at desc);

alter table public.employee_payroll_components enable row level security;
alter table public.notifications enable row level security;