-- BluePrint HR PostgreSQL schema for Supabase
-- Applied to the connected Supabase project on 2026-10-03.
-- The ASP.NET Core API connects directly to PostgreSQL; Supabase Data API access
-- remains protected by RLS and no public policies are granted by this migration.

create table if not exists public.tenants (
  id integer generated by default as identity primary key,
  company_name text not null,
  kra_pin text,
  email text,
  phone text,
  address text,
  subdomain text,
  status text not null default 'Active',
  created_at timestamptz not null default now()
);
create unique index if not exists ix_tenants_subdomain on public.tenants(subdomain) where subdomain is not null;

create table if not exists public.branches (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  name text not null,
  code text,
  location text,
  created_at timestamptz not null default now()
);
create unique index if not exists ix_branches_tenant_name on public.branches(tenant_id,name);

create table if not exists public.departments (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  branch_id integer references public.branches(id) on delete set null,
  name text not null,
  code text,
  created_at timestamptz not null default now()
);
create unique index if not exists ix_departments_tenant_name on public.departments(tenant_id,name);

create table if not exists public.designations (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  name text not null
);
create unique index if not exists ix_designations_tenant_name on public.designations(tenant_id,name);

create table if not exists public.grades (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  name text not null,
  level text,
  min_salary numeric(18,2) not null,
  max_salary numeric(18,2) not null
);

create table if not exists public.employment_types (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  name text not null,
  description text
);
create unique index if not exists ix_employment_types_tenant_name on public.employment_types(tenant_id,name);

create table if not exists public.employees (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  employee_no text not null,
  payroll_no text,
  first_name text not null,
  middle_name text,
  last_name text not null,
  gender text,
  date_of_birth timestamptz,
  id_no text,
  kra_pin text not null,
  nssf_no text,
  shif_no text,
  phone text,
  email text,
  branch_id integer references public.branches(id) on delete set null,
  department_id integer references public.departments(id) on delete set null,
  designation_id integer references public.designations(id) on delete set null,
  grade_id integer references public.grades(id) on delete set null,
  employment_type_id integer references public.employment_types(id) on delete set null,
  employment_date timestamptz,
  termination_date timestamptz,
  employment_status text not null default 'Active',
  basic_salary numeric(18,2) not null,
  bank_name text,
  bank_branch text,
  account_number text
);
create unique index if not exists ix_employees_tenant_employee_no on public.employees(tenant_id,employee_no);

create table if not exists public.users (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  name text not null,
  email text not null,
  password_hash text not null,
  role text not null default 'Employee',
  employee_id integer references public.employees(id) on delete set null,
  created_at timestamptz not null default now(),
  last_signed_in timestamptz
);
create unique index if not exists ix_users_tenant_email on public.users(tenant_id,email);

create table if not exists public.payroll_periods (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  name text not null,
  month integer not null,
  year integer not null,
  status text not null default 'Open',
  processed_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists ix_payroll_periods_tenant_year_month on public.payroll_periods(tenant_id,year,month);

create table if not exists public.payroll_transactions (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  payroll_period_id integer not null references public.payroll_periods(id) on delete cascade,
  employee_id integer not null references public.employees(id) on delete restrict,
  basic_salary numeric(18,2) not null,
  allowances numeric(18,2) not null,
  gross_pay numeric(18,2) not null,
  taxable_pay numeric(18,2) not null,
  paye numeric(18,2) not null,
  personal_relief numeric(18,2) not null,
  nssf numeric(18,2) not null,
  shif numeric(18,2) not null,
  housing_levy numeric(18,2) not null,
  other_deductions numeric(18,2) not null,
  total_deductions numeric(18,2) not null,
  net_pay numeric(18,2) not null,
  status text not null default 'Draft',
  created_at timestamptz not null default now()
);
create unique index if not exists ix_payroll_transactions_tenant_period_employee on public.payroll_transactions(tenant_id,payroll_period_id,employee_id);

create table if not exists public.leave_types (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  name text not null,
  default_days integer not null,
  paid boolean not null default true,
  description text
);
create unique index if not exists ix_leave_types_tenant_name on public.leave_types(tenant_id,name);

create table if not exists public.leave_balances (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  employee_id integer not null references public.employees(id) on delete restrict,
  leave_type_id integer not null references public.leave_types(id) on delete restrict,
  year integer not null,
  allocated_days numeric(9,2) not null,
  used_days numeric(9,2) not null
);
create unique index if not exists ix_leave_balances_tenant_employee_type_year on public.leave_balances(tenant_id,employee_id,leave_type_id,year);

create table if not exists public.leave_requests (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  employee_id integer not null references public.employees(id) on delete restrict,
  leave_type_id integer not null references public.leave_types(id) on delete restrict,
  start_date timestamptz not null,
  end_date timestamptz not null,
  days_requested numeric(9,2) not null,
  reason text,
  status text not null default 'Pending',
  reviewed_by integer references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.audit_logs (
  id integer generated by default as identity primary key,
  tenant_id integer not null references public.tenants(id) on delete restrict,
  user_id integer references public.users(id) on delete set null,
  user_name text,
  action text not null,
  entity_type text not null,
  entity_id integer,
  details text,
  ip_address text,
  created_at timestamptz not null default now()
);
create index if not exists ix_audit_logs_tenant_created_at on public.audit_logs(tenant_id,created_at);

create table if not exists public.report_definitions (
  id integer generated by default as identity primary key,
  name text not null,
  description text not null,
  report_path text not null,
  enabled boolean not null default true
);
create unique index if not exists ix_report_definitions_name on public.report_definitions(name);

alter table public.tenants enable row level security;
alter table public.branches enable row level security;
alter table public.departments enable row level security;
alter table public.designations enable row level security;
alter table public.grades enable row level security;
alter table public.employment_types enable row level security;
alter table public.employees enable row level security;
alter table public.users enable row level security;
alter table public.payroll_periods enable row level security;
alter table public.payroll_transactions enable row level security;
alter table public.leave_types enable row level security;
alter table public.leave_balances enable row level security;
alter table public.leave_requests enable row level security;
alter table public.audit_logs enable row level security;
alter table public.report_definitions enable row level security;
